### PR TITLE
add about , gallery section

### PR DESCRIPTION
**Pull request by adhilsalim**

### CODE REVIEW

**Comment by adhilsalim** [comment]
Image access denied #6 @zameel7 @Vivek0306

**Comment by zameel7** [comment]
> Image access denied #6 @zameel7 @Vivek0306

image


Use the urls as seen in the ss above. You will get that when you edit the issue you raised in the repo.

**Comment by zameel7** [comment]
image


Please edit this and make the contents inside each of the cards to limit at a certain height. You could do this by adding a ```read more``` button when a certain letter count cap reaches.

**Review by zameel7 — CHANGES_REQUESTED** [review]
Please make the changes mentioned above and re-request the review.

**Comment by adhilsalim** [comment]
> Please edit this and make the contents inside each of the cards to limit at a certain height. You could do this by adding a `read more` button when a certain letter count cap reaches.

We are actually providing a `read more` button which redirects to the webpages as in [TEDx AJCE](https://tedxajce.in/). How about setting a `min-height` ?

**Comment by tedxajce** [comment]
Also no need to add a separate info regarding each TED even, just the image is fine. Try and change the card header background to more of a red color matching our theme, if it is not an image.

image

**Comment by zameel7** [comment]
> > Please edit this and make the contents inside each of the cards to limit at a certain height. You could do this by adding a `read more` button when a certain letter count cap reaches.
> 
> We are actually providing a `read more` button which redirects to the webpages as in [TEDx AJCE](https://tedxajce.in/). How about setting a `min-height` ?

That would be fine too. Just make it look the same.

**Comment by zameel7** [comment]
> Also no need to add a separate info regarding each TED even, just the image is fine. Try and change the card header background to more of a red color matching our theme, if it is not an image.
> 
> image

@adhilsalim , did you check this out?

**Comment by adhilsalim** [comment]
> Try and change the card header background to more of a red color matching our theme, if it is not an image.

Not an image, it's a gradient background. And the color is set using CSS variables defined in color.css which can be changed later.

**Comment by adhilsalim** [comment]
> Also no need to add a separate info regarding each TED even, just the image is fine.

commented the title

**Comment by adhilsalim** [comment]
> @adhilsalim , did you check this out?

Yes, but not added in the previous commit.

**Comment by zameel7** [comment]
Raise a PR of that commit.

**Comment by zameel7** [comment]
image

@adhilsalim

**Review by zameel7 — COMMENTED** [review]
I'll raise a new issue for the remaining work

**Pull request merged**
